### ISSUE TITLE
stored procs

### ISSUE THREAD

**Issue by mninawa** [meysamhadeli/booking-microservices#277]
Hi Guys
how would you execute a stored proc, can you please give a guide

**Comment by meysamhadeli** [comment]
> Hi Guys how would you execute a stored proc, can you please give a guide

Hi,
In this project, we don't use store procedure, because maintain of store procedure is a little hard. And with ef-core and linq we have more flexibility and easy to maintain.
For using store procedure, you can use dapper or ef-core for calling store procedure directly.
