### ISSUE TITLE
An event has multiple consumer then what will be happen ?

### ISSUE THREAD

**Issue by akbarbd** [meysamhadeli/booking-microservices#42]

**Comment by akbarbd** [comment]
Yes, you are right. But it works when debug the code, without debug it consume first consumer then change PersistMessage messageStatus.

**Comment by meysamhadeli** [comment]
> Yes, you are right. But it works when debug the code, without debug it consume first consumer then change PersistMessage messageStatus.

I added a sample for `RegisterNewUser endpoint` and after that publish an event `user-created` and consume this event in multiple consumers (Flight-Services and Passenger-Services) and it's work correctly.

You can check these changes in this PR: #43
