### ISSUE TITLE
Save Problem

### ISSUE THREAD

**Issue by akbarbd** [meysamhadeli/booking-microservices#53]
Brother,
I am facing a problem when saving data. Though I have commented savechanges method, data saves in database.
**In my scenario on this table there is no domain events.** 
 var newAircraft = await _flightDbContext.Aircraft.AddAsync(aircraftEntity, cancellationToken);
  //await _flightDbContext.SaveChangesAsync(cancellationToken);

**Comment by meysamhadeli** [comment]
> Brother, I am facing a problem when saving data. Though I have commented savechanges method, data saves in database. **In my scenario on this table there is no domain events.** var newAircraft = await _flightDbContext.Aircraft.AddAsync(aircraftEntity, cancellationToken); //await _flightDbContext.SaveChangesAsync(cancellationToken);

> Note: I have a behavior on top of mediatR and it saves data automaticly without call SavechangeAsync. you can find it this code below: [EfTxBehavior](https://github.com/meysamhadeli/booking-microservices/blob/main/src/BuildingBlocks/EFCore/EfTxBehavior.cs#L64)

**Comment by meysamhadeli** [comment]
> In my services i use some `pipleline behaviour` on top of `mediatR` for example (caching, validating, logging, ...). 
You can remove `EfTxBehavior` from `mediatR pipeline` and use simple approach to save your data.
 Remove `EfTxBehavior` from pipelines here: 
https://github.com/meysamhadeli/booking-microservices/blob/main/src/Services/Flight/src/Flight/Extensions/MediatRExtensions.cs#L17).
You can check this article about my solution for use some pipeline for handle EF-Core level: 
http://www.kamilgrzybek.com/design/handling-domain-events-missing-part/

**Comment by akbarbd** [comment]
Brother, thanks for your replay,
i am understanding.
